DROP TABLE IF EXISTS BENEFICIO;

CREATE TABLE BENEFICIO (
    ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(255) DEFAULT '',
    VALOR DECIMAL(15,2) NOT NULL,
    ATIVO BOOLEAN DEFAULT TRUE,
    VERSION BIGINT DEFAULT 0
);